/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelbooking;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ibnuk
 */
public class Home extends javax.swing.JFrame {
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        Connect();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelbooking", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipekamarbtngroup = new javax.swing.ButtonGroup();
        kapasitaskamarbtngroup = new javax.swing.ButtonGroup();
        tipekamarbtngrpbooking = new javax.swing.ButtonGroup();
        kapasitaskamarbtngrpbooking = new javax.swing.ButtonGroup();
        menupanel = new javax.swing.JPanel();
        checkoutbtn = new javax.swing.JButton();
        roombookingbtn = new javax.swing.JButton();
        checkinbtn = new javax.swing.JButton();
        cancelbookingbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        roomsbutton = new javax.swing.JButton();
        roomsbutton1 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        checkinpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        textnamalengkap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textemail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textalamat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textkota = new javax.swing.JTextField();
        textnomorhp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        radioregular = new javax.swing.JRadioButton();
        radiopremium = new javax.swing.JRadioButton();
        radioexecutive = new javax.swing.JRadioButton();
        radiosingle = new javax.swing.JRadioButton();
        radiodouble = new javax.swing.JRadioButton();
        radiotriple = new javax.swing.JRadioButton();
        tanggalcheckin = new com.toedter.calendar.JDateChooser();
        tanggalcheckout = new com.toedter.calendar.JDateChooser();
        labelroomid = new javax.swing.JTextField();
        btncheckinsubmit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        checkoutpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        textnokamarcheckout = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtnamatamucheckout = new javax.swing.JTextField();
        roombookingpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        textnamalengkap1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        textemail1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        textalamat1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        textkota1 = new javax.swing.JTextField();
        textnomorhp1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        radioregular1 = new javax.swing.JRadioButton();
        radiopremium1 = new javax.swing.JRadioButton();
        radioexecutive1 = new javax.swing.JRadioButton();
        radiosingle1 = new javax.swing.JRadioButton();
        radiodouble1 = new javax.swing.JRadioButton();
        radiotriple1 = new javax.swing.JRadioButton();
        tanggalcheckin1 = new com.toedter.calendar.JDateChooser();
        tanggalcheckout1 = new com.toedter.calendar.JDateChooser();
        textroomidbooking = new javax.swing.JTextField();
        btnroombookingsubmit = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        cancelbookingpanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        textnokamarcancel = new javax.swing.JTextField();
        clearbtncancel = new javax.swing.JButton();
        submitbtncancel = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        txtcancelnama = new javax.swing.JTextField();
        roomspanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        scrolltabel = new javax.swing.JScrollPane();
        tabelrooms = new javax.swing.JTable();
        tamupanel = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeltamu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PLAZA HOTEL - Home");

        menupanel.setBackground(new java.awt.Color(64, 115, 158));

        checkoutbtn.setBackground(new java.awt.Color(52, 152, 219));
        checkoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutbtn.setText("Check Out");
        checkoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutbtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkoutbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkoutbtnMouseReleased(evt);
            }
        });

        roombookingbtn.setBackground(new java.awt.Color(52, 152, 219));
        roombookingbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roombookingbtn.setForeground(new java.awt.Color(255, 255, 255));
        roombookingbtn.setText("Room Booking");
        roombookingbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roombookingbtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roombookingbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                roombookingbtnMouseReleased(evt);
            }
        });

        checkinbtn.setBackground(new java.awt.Color(52, 152, 219));
        checkinbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkinbtn.setForeground(new java.awt.Color(255, 255, 255));
        checkinbtn.setText("Check In");
        checkinbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkinbtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkinbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkinbtnMouseReleased(evt);
            }
        });

        cancelbookingbtn.setBackground(new java.awt.Color(52, 152, 219));
        cancelbookingbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelbookingbtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelbookingbtn.setText("Cancel Booking");
        cancelbookingbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelbookingbtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelbookingbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelbookingbtnMouseReleased(evt);
            }
        });

        logoutbtn.setBackground(new java.awt.Color(52, 152, 219));
        logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutbtn.setText("Logout");
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutbtnMouseReleased(evt);
            }
        });

        roomsbutton.setBackground(new java.awt.Color(52, 152, 219));
        roomsbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roomsbutton.setForeground(new java.awt.Color(255, 255, 255));
        roomsbutton.setText("Rooms");
        roomsbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomsbuttonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roomsbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                roomsbuttonMouseReleased(evt);
            }
        });
        roomsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomsbuttonActionPerformed(evt);
            }
        });

        roomsbutton1.setBackground(new java.awt.Color(52, 152, 219));
        roomsbutton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roomsbutton1.setForeground(new java.awt.Color(255, 255, 255));
        roomsbutton1.setText("Tamu");
        roomsbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomsbutton1MouseClicked(evt);
            }
        });
        roomsbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomsbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menupanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roomsbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelbookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roombookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(checkinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roombookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelbookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roomsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roomsbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        header.setBackground(new java.awt.Color(64, 115, 158));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hello,");

        displayname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        displayname.setForeground(new java.awt.Color(255, 255, 255));
        displayname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayname, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(displayname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        mainpanel.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Check In");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.darkGray));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.darkGray));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Nama Lengkap");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Email");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Alamat");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Kota");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Nomor HP");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Data Diri");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(104, 104, 104))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textkota, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textalamat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textemail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textnamalengkap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(textnomorhp))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textnamalengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textnomorhp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Data Kamar");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Tipe Kamar");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Kapasitas Kamar");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Tanggal Check In");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Tanggal Check Out");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Room id");

        tipekamarbtngroup.add(radioregular);
        radioregular.setText("Regular");

        tipekamarbtngroup.add(radiopremium);
        radiopremium.setText("Premium");

        tipekamarbtngroup.add(radioexecutive);
        radioexecutive.setText("Executive");

        kapasitaskamarbtngroup.add(radiosingle);
        radiosingle.setText("Single");

        kapasitaskamarbtngroup.add(radiodouble);
        radiodouble.setText("Double");

        kapasitaskamarbtngroup.add(radiotriple);
        radiotriple.setText("Triple");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(265, 265, 265))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tanggalcheckin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(tanggalcheckout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelroomid))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioregular)
                                    .addComponent(radiosingle))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiodouble)
                                    .addComponent(radiopremium))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiotriple)
                                    .addComponent(radioexecutive))))
                        .addGap(139, 139, 139))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel13)
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioregular)
                            .addComponent(radiopremium)
                            .addComponent(radioexecutive))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radiosingle)
                            .addComponent(radiodouble)
                            .addComponent(radiotriple))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(tanggalcheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(tanggalcheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(labelroomid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        btncheckinsubmit.setText("Submit");
        btncheckinsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckinsubmitActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncheckinsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncheckinsubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout checkinpanelLayout = new javax.swing.GroupLayout(checkinpanel);
        checkinpanel.setLayout(checkinpanelLayout);
        checkinpanelLayout.setHorizontalGroup(
            checkinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkinpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(checkinpanelLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        checkinpanelLayout.setVerticalGroup(
            checkinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkinpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainpanel.add(checkinpanel, "card2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Check Out");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Nomor Kamar");

        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setText("Nama");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel33))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(clearbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textnokamarcheckout)
                    .addComponent(txtnamatamucheckout))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(199, 199, 199)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtnamatamucheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(textnokamarcheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(clearbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(363, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout checkoutpanelLayout = new javax.swing.GroupLayout(checkoutpanel);
        checkoutpanel.setLayout(checkoutpanelLayout);
        checkoutpanelLayout.setHorizontalGroup(
            checkoutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        checkoutpanelLayout.setVerticalGroup(
            checkoutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        mainpanel.add(checkoutpanel, "card3");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Room Booking");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.darkGray));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.darkGray));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Nama Lengkap");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Email");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Alamat");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Kota");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Nomor HP");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Data Diri");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel25))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(104, 104, 104))))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textkota1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textalamat1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textemail1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textnamalengkap1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(textnomorhp1))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel25)
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(textnamalengkap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(textemail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(textalamat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(textkota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(textnomorhp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Data Kamar");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Tipe Kamar");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Kapasitas Kamar");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Tanggal Check In");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setText("Tanggal Check Out");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setText("Room id");

        tipekamarbtngrpbooking.add(radioregular1);
        radioregular1.setText("Regular");

        tipekamarbtngrpbooking.add(radiopremium1);
        radiopremium1.setText("Premium");

        tipekamarbtngrpbooking.add(radioexecutive1);
        radioexecutive1.setText("Executive");

        kapasitaskamarbtngrpbooking.add(radiosingle1);
        radiosingle1.setText("Single");

        kapasitaskamarbtngrpbooking.add(radiodouble1);
        radiodouble1.setText("Double");

        kapasitaskamarbtngrpbooking.add(radiotriple1);
        radiotriple1.setText("Triple");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tanggalcheckin1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tanggalcheckout1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(textroomidbooking))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioregular1)
                            .addComponent(radiosingle1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiodouble1)
                            .addComponent(radiopremium1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiotriple1)
                            .addComponent(radioexecutive1)))
                    .addComponent(jLabel26))
                .addGap(115, 115, 115))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioregular1)
                            .addComponent(radiopremium1)
                            .addComponent(radioexecutive1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radiosingle1)
                            .addComponent(radiodouble1)
                            .addComponent(radiotriple1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(tanggalcheckin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(tanggalcheckout1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(textroomidbooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        btnroombookingsubmit.setText("Submit");
        btnroombookingsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroombookingsubmitActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnroombookingsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnroombookingsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roombookingpanelLayout = new javax.swing.GroupLayout(roombookingpanel);
        roombookingpanel.setLayout(roombookingpanelLayout);
        roombookingpanelLayout.setHorizontalGroup(
            roombookingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roombookingpanelLayout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel4)
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(roombookingpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roombookingpanelLayout.setVerticalGroup(
            roombookingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roombookingpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainpanel.add(roombookingpanel, "card4");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Cancel Booking");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setText("Nomor Kamar");

        clearbtncancel.setText("Clear");
        clearbtncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtncancelActionPerformed(evt);
            }
        });

        submitbtncancel.setText("Submit");
        submitbtncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtncancelActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setText("Nama");

        javax.swing.GroupLayout cancelbookingpanelLayout = new javax.swing.GroupLayout(cancelbookingpanel);
        cancelbookingpanel.setLayout(cancelbookingpanelLayout);
        cancelbookingpanelLayout.setHorizontalGroup(
            cancelbookingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelbookingpanelLayout.createSequentialGroup()
                .addGroup(cancelbookingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancelbookingpanelLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel5))
                    .addGroup(cancelbookingpanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(cancelbookingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34))
                        .addGap(44, 44, 44)
                        .addGroup(cancelbookingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(cancelbookingpanelLayout.createSequentialGroup()
                                .addComponent(clearbtncancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(submitbtncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textnokamarcancel, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(txtcancelnama))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        cancelbookingpanelLayout.setVerticalGroup(
            cancelbookingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelbookingpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(227, 227, 227)
                .addGroup(cancelbookingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel34)
                    .addComponent(txtcancelnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cancelbookingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(textnokamarcancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(cancelbookingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitbtncancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearbtncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(464, Short.MAX_VALUE))
        );

        mainpanel.add(cancelbookingpanel, "card5");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Rooms");

        tabelrooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No Kamar", "Tipe Kamar", "Kapasitas Kamar", "Tanggal Check In", "Tanggal Check out", "Kosong"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrolltabel.setViewportView(tabelrooms);

        javax.swing.GroupLayout roomspanelLayout = new javax.swing.GroupLayout(roomspanel);
        roomspanel.setLayout(roomspanelLayout);
        roomspanelLayout.setHorizontalGroup(
            roomspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomspanelLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(roomspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrolltabel, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        roomspanelLayout.setVerticalGroup(
            roomspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrolltabel, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE))
        );

        mainpanel.add(roomspanel, "card6");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel35.setText("Tamu");

        tabeltamu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Room ID", "Nama", "Email", "Alamat", "Kota", "Nomor HP", "Checkin", "Checkout", "Tipe Kamar", "Kapasitas Kamar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabeltamu);

        javax.swing.GroupLayout tamupanelLayout = new javax.swing.GroupLayout(tamupanel);
        tamupanel.setLayout(tamupanelLayout);
        tamupanelLayout.setHorizontalGroup(
            tamupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tamupanelLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tamupanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        tamupanelLayout.setVerticalGroup(
            tamupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tamupanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainpanel.add(tamupanel, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkinbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkinbtnMousePressed
        // TODO add your handling code here:
        checkinbtn.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_checkinbtnMousePressed

    private void checkinbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkinbtnMouseReleased
        // TODO add your handling code here:
        checkinbtn.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_checkinbtnMouseReleased

    private void checkoutbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutbtnMousePressed
        // TODO add your handling code here:
        checkoutbtn.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_checkoutbtnMousePressed

    private void checkoutbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutbtnMouseReleased
        // TODO add your handling code here:
        checkoutbtn.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_checkoutbtnMouseReleased

    private void roombookingbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roombookingbtnMousePressed
        // TODO add your handling code here:
        roombookingbtn.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_roombookingbtnMousePressed

    private void roombookingbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roombookingbtnMouseReleased
        // TODO add your handling code here:
        roombookingbtn.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_roombookingbtnMouseReleased

    private void cancelbookingbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbookingbtnMousePressed
        // TODO add your handling code here:
        cancelbookingbtn.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_cancelbookingbtnMousePressed

    private void cancelbookingbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbookingbtnMouseReleased
        // TODO add your handling code here:
        cancelbookingbtn.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_cancelbookingbtnMouseReleased

    private void roomsbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsbuttonMousePressed
        // TODO add your handling code here:
        roomsbutton.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_roomsbuttonMousePressed

    private void roomsbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsbuttonMouseReleased
        // TODO add your handling code here:
        roomsbutton.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_roomsbuttonMouseReleased

    private void logoutbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMousePressed
        // TODO add your handling code here:
        logoutbtn.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_logoutbtnMousePressed

    private void logoutbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseReleased
        // TODO add your handling code here:
        logoutbtn.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_logoutbtnMouseReleased

    private void checkinbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkinbtnMouseClicked
        // TODO add your handling code here:
        // remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // adding panel
        mainpanel.add(checkinpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_checkinbtnMouseClicked

    private void checkoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutbtnMouseClicked
        // TODO add your handling code here:
        // remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // adding panel
        mainpanel.add(checkoutpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_checkoutbtnMouseClicked

    private void roombookingbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roombookingbtnMouseClicked
        // TODO add your handling code here:
        // remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // adding panel
        mainpanel.add(roombookingpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_roombookingbtnMouseClicked

    private void cancelbookingbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbookingbtnMouseClicked
        // TODO add your handling code here:
        // remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // adding panel
        mainpanel.add(cancelbookingpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_cancelbookingbtnMouseClicked

    private void roomsbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsbuttonMouseClicked
        // TODO add your handling code here:
        // remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // adding panel
        mainpanel.add(roomspanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_roomsbuttonMouseClicked

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
        // TODO add your handling code here:
        int dialogbtn = JOptionPane.YES_NO_OPTION;
        int dialogRes = JOptionPane.showConfirmDialog(this, "apakah anda ingin keluar ?");
        this.setVisible(false);
        if (dialogRes == 0) {
            new Login().setVisible(true);
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void roomsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomsbuttonActionPerformed
         // TODO add your handling code here:
            String sql = "SELECT * FROM kamarhotel";
        
        try {        
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)tabelrooms.getModel();
            model.setRowCount(0);
            while (rs.next()) {                
                model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_roomsbuttonActionPerformed

    private void btncheckinsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckinsubmitActionPerformed
        // Set Value radio button
        radioregular.setActionCommand("Regular");
        radiopremium.setActionCommand("Premium");
        radioexecutive.setActionCommand("Executive");
        
        radiosingle.setActionCommand("Single");
        radiodouble.setActionCommand("Double");
        radiotriple.setActionCommand("Triple");

        // get data for sql:
        String nama = textnamalengkap.getText();
        String email = textemail.getText();
        String alamat = textalamat.getText();
        String kota = textkota.getText();
        String nohp = textnomorhp.getText();
        String nokamar = labelroomid.getText();
        String kapasitas = kapasitaskamarbtngroup.getSelection().getActionCommand();
        String tipekamar = tipekamarbtngroup.getSelection().getActionCommand();
        java.sql.Date tglcheckin = new java.sql.Date(tanggalcheckin.getDate().getTime());
        java.sql.Date tglcheckout = new java.sql.Date(tanggalcheckout.getDate().getTime());
        
                
                       
        String sqlinserttamu = "INSERT INTO `tamuhotel`(`roomid`, `nama`, `email`, `alamat`, `kota`, `nohandphone`, `checkin`, `checkout`, `tipekamar`, `kapasitaskamar`) "
                             + "VALUES ('"+nokamar+"','"+nama+"','"+email+"','"+alamat+"','"+kota+"','"+nohp+"','"+tglcheckin+"','"+tglcheckout+"','"+tipekamar+"','"+kapasitas+"')";
        
        String updatekamar = "UPDATE `kamarhotel` SET `tgl-in`='"+tglcheckin+"',`tgl-out`='"+tglcheckout+"',`kosong`=\"0\" WHERE nokamar LIKE '"+nokamar+"'";
             
        
        try {
            pst =  con.prepareStatement(sqlinserttamu);
            PreparedStatement pst1 = con.prepareStatement(updatekamar);
            int rs = pst.executeUpdate();
            int rs1 = pst1.executeUpdate();
            
           JOptionPane.showMessageDialog(this, "Data berhasil dimasukkan", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btncheckinsubmitActionPerformed

    private void roomsbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomsbutton1ActionPerformed
        // TODO add your handling code here:
        
        String sql = "SELECT * FROM tamuhotel";
        
        try {        
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)tabeltamu.getModel();
            model.setRowCount(0);
            while (rs.next()) {                
                model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_roomsbutton1ActionPerformed

    private void roomsbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsbutton1MouseClicked
        // TODO add your handling code here:
        // remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // adding panel
        mainpanel.add(tamupanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_roomsbutton1MouseClicked

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        txtnamatamucheckout.setText(null);
        textnokamarcheckout.setText(null);
    }//GEN-LAST:event_clearbtnActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        String nama = txtnamatamucheckout.getText();
        String nokamar =  textnokamarcheckout.getText();
        
        String sql = "DELETE FROM `tamuhotel` WHERE roomid LIKE '"+nokamar+"' and nama LIKE '"+nama+"%'";
        String sql2 = "UPDATE `kamarhotel` SET `kosong`=\"1\" WHERE nokamar LIKE '"+nokamar+"'";
        
        try {
            pst = con.prepareStatement(sql);
            PreparedStatement pst2 = con.prepareStatement(sql2);
            int rs = pst.executeUpdate();
            int rs1 = pst2.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Tamu berhasil checkout", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_submitbtnActionPerformed

    private void btnroombookingsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroombookingsubmitActionPerformed
        // TODO add your handling code here:
        // Set Value radio button
        radioregular1.setActionCommand("Regular");
        radiopremium1.setActionCommand("Premium");
        radioexecutive1.setActionCommand("Executive");
        
        radiosingle1.setActionCommand("Single");
        radiodouble1.setActionCommand("Double");
        radiotriple1.setActionCommand("Triple");

        // get data for sql:
        String nama = textnamalengkap1.getText();
        String email = textemail1.getText();
        String alamat = textalamat1.getText();
        String kota = textkota1.getText();
        String nohp = textnomorhp1.getText();
        String nokamar = textroomidbooking.getText();
        String kapasitas = kapasitaskamarbtngrpbooking.getSelection().getActionCommand();
        String tipekamar = tipekamarbtngrpbooking.getSelection().getActionCommand();
        java.sql.Date tglcheckin = new java.sql.Date(tanggalcheckin1.getDate().getTime());
        java.sql.Date tglcheckout = new java.sql.Date(tanggalcheckout1.getDate().getTime());
        
                
                       
        String sqlinserttamu = "INSERT INTO `tamuhotel`(`roomid`, `nama`, `email`, `alamat`, `kota`, `nohandphone`, `checkin`, `checkout`, `tipekamar`, `kapasitaskamar`) "
                             + "VALUES ('"+nokamar+"','"+nama+"','"+email+"','"+alamat+"','"+kota+"','"+nohp+"','"+tglcheckin+"','"+tglcheckout+"','"+tipekamar+"','"+kapasitas+"')";
        
        String updatekamar = "UPDATE `kamarhotel` SET `tgl-in`='"+tglcheckin+"',`tgl-out`='"+tglcheckout+"',`kosong`=\"0\" WHERE nokamar LIKE '"+nokamar+"'";
             
        
        try {
            pst =  con.prepareStatement(sqlinserttamu);
            PreparedStatement pst1 = con.prepareStatement(updatekamar);
            int rs = pst.executeUpdate();
            int rs1 = pst1.executeUpdate();
            
           JOptionPane.showMessageDialog(this, "Data berhasil dimasukkan", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnroombookingsubmitActionPerformed

    private void clearbtncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtncancelActionPerformed
        // TODO add your handling code here:
        txtcancelnama.setText(null);
        textnokamarcancel.setText(null);
    }//GEN-LAST:event_clearbtncancelActionPerformed

    private void submitbtncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtncancelActionPerformed
        // TODO add your handling code here:
        String nama = txtcancelnama.getText();
        String nokamar =  textnokamarcancel.getText();
        
        String sql = "DELETE FROM `tamuhotel` WHERE roomid LIKE '"+nokamar+"' and nama LIKE '"+nama+"%'";
        String sql2 = "UPDATE `kamarhotel` SET `kosong`=\"1\" WHERE nokamar LIKE '"+nokamar+"'";
        
        try {
            pst = con.prepareStatement(sql);
            PreparedStatement pst2 = con.prepareStatement(sql2);
            int rs = pst.executeUpdate();
            int rs1 = pst2.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Tamu berhasil Cancel Bookingt", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitbtncancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        textnamalengkap.setText(null);
        textemail.setText(null);
        textalamat.setText(null);
        textkota.setText(null);
        textnomorhp.setText(null);
        kapasitaskamarbtngroup.clearSelection();
        tipekamarbtngroup.clearSelection();
        labelroomid.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        textnamalengkap1.setText(null);
        textemail1.setText(null);
        textalamat1.setText(null);
        textkota1.setText(null);
        textnomorhp1.setText(null);
        kapasitaskamarbtngrpbooking.clearSelection();
        tipekamarbtngrpbooking.clearSelection();
        textroomidbooking.setText(null);
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckinsubmit;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnroombookingsubmit;
    private javax.swing.JButton cancelbookingbtn;
    private javax.swing.JPanel cancelbookingpanel;
    private javax.swing.JButton checkinbtn;
    private javax.swing.JPanel checkinpanel;
    private javax.swing.JButton checkoutbtn;
    private javax.swing.JPanel checkoutpanel;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton clearbtncancel;
    public static final javax.swing.JLabel displayname = new javax.swing.JLabel();
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup kapasitaskamarbtngroup;
    private javax.swing.ButtonGroup kapasitaskamarbtngrpbooking;
    private javax.swing.JTextField labelroomid;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel menupanel;
    private javax.swing.JRadioButton radiodouble;
    private javax.swing.JRadioButton radiodouble1;
    private javax.swing.JRadioButton radioexecutive;
    private javax.swing.JRadioButton radioexecutive1;
    private javax.swing.JRadioButton radiopremium;
    private javax.swing.JRadioButton radiopremium1;
    private javax.swing.JRadioButton radioregular;
    private javax.swing.JRadioButton radioregular1;
    private javax.swing.JRadioButton radiosingle;
    private javax.swing.JRadioButton radiosingle1;
    private javax.swing.JRadioButton radiotriple;
    private javax.swing.JRadioButton radiotriple1;
    private javax.swing.JButton roombookingbtn;
    private javax.swing.JPanel roombookingpanel;
    private javax.swing.JButton roomsbutton;
    private javax.swing.JButton roomsbutton1;
    private javax.swing.JPanel roomspanel;
    private javax.swing.JScrollPane scrolltabel;
    private javax.swing.JButton submitbtn;
    private javax.swing.JButton submitbtncancel;
    private javax.swing.JTable tabelrooms;
    private javax.swing.JTable tabeltamu;
    private javax.swing.JPanel tamupanel;
    private com.toedter.calendar.JDateChooser tanggalcheckin;
    private com.toedter.calendar.JDateChooser tanggalcheckin1;
    private com.toedter.calendar.JDateChooser tanggalcheckout;
    private com.toedter.calendar.JDateChooser tanggalcheckout1;
    private javax.swing.JTextField textalamat;
    private javax.swing.JTextField textalamat1;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField textemail1;
    private javax.swing.JTextField textkota;
    private javax.swing.JTextField textkota1;
    private javax.swing.JTextField textnamalengkap;
    private javax.swing.JTextField textnamalengkap1;
    private javax.swing.JTextField textnokamarcancel;
    private javax.swing.JTextField textnokamarcheckout;
    private javax.swing.JTextField textnomorhp;
    private javax.swing.JTextField textnomorhp1;
    private javax.swing.JTextField textroomidbooking;
    private javax.swing.ButtonGroup tipekamarbtngroup;
    private javax.swing.ButtonGroup tipekamarbtngrpbooking;
    private javax.swing.JTextField txtcancelnama;
    private javax.swing.JTextField txtnamatamucheckout;
    // End of variables declaration//GEN-END:variables
}
